#!/bin/env python

"""
usage: mdms [--version] <command> [<args>...]

options:
    --version   display version information

the available commands are:
    search      Search for a document

use 'mdms help <command>' for information about a command
"""

from docopt import docopt
import config
import database
import filesystem

def main():
    configuration = config.parse('config.toml')
    db = database.get_instance(configuration)
    fs = filesystem.get_instance(configuration)

    args = docopt(__doc__,
            version = "mdms version 0.0.0",
            options_first = True)
    argv = [args['<command>']] + args['<args>']

    if args['<command>'] == 'search':
        import mdms_search
        mdms_search.main(argv, db, fs)


if __name__ == '__main__':
    main()
