#!/bin/env python

"""
usage: mdms [--version] [-h] <command> [<args>...]

options:
    --version   display version information
    --help, -h  display help information

the available commands are:
    search      Search for a document
    create      Create a new document
    modify      Modify metadata or files
    remove      Remove a document
    web         Start webserver

use 'mdms <command> -h' for information about a command
"""

from docopt import docopt
import config
import database
import filesystem

def main():
    configuration = config.parse('config.toml')
    db = database.get_instance(configuration)
    fs = filesystem.get_instance(configuration)

    args = docopt(__doc__,
            version = "mdms version 0.0.0",
            options_first = True)
    argv = [args['<command>']] + args['<args>']

    if args['<command>'] == 'search':
        import mdms_search
        mdms_search.main(argv, db, fs)
    elif args['<command>'] == 'create':
        import mdms_create
        mdms_create.main(argv, db, fs)
    elif args['<command>'] == 'modify':
        import mdms_modify
        mdms_modify.main(argv, db, fs)
    elif args['<command>'] == 'remove':
        import mdms_remove
        mdms_remove.main(argv, db, fs)
    elif args['<command>'] == 'web':
        import mdms_web
        mdms_web.main(argv, db, fs)
    else:
        print(__doc__)


if __name__ == '__main__':
    main()
